title: 前端开发者大会
subtitle: ""
description: ""
author: silence
language: zh-cn 
timezone: UTC
root: /
theme: navy
deploy:
  type: git
  branch: master
  repo: git@github.com:silenceM/silenceM.github.io.git