<div class="mettingItem">
  <div class="left">
    <div class="leftContent">
      <div class="name">{{name}}</div>
      <p>活动时间：{{mettingDate}}</p>
      <p>活动地址：{{address}}</p>
      <p>XXXXXX 特性专场 | XXXX特性专场 | 女性专场</p>
    </div>
    <!-- <img src={{rightImg}} alt=""> -->
  </div>
  <div class="right">
    <a href="">
      <button class="btn btn-blue">查看详细信息</button>
    </a>
    <a href="">
      <button class="btn btn-blue">我要买票</button>
    </a>
  </div>
</div>